/**
 * Display-time translation for incident content.
 *
 * Incident prose is generated by the API and stored in English (see
 * migration 019). Translating at write time would be wrong: an org has many
 * users with different locales, and switching locale later could not
 * retranslate stored rows. So the API records stable keys — `rule_id`,
 * `root_cause_key`, `suggested_fix_key` — and the prose is resolved here,
 * per viewer, at render time.
 *
 * This catalog deliberately lives outside `messages/*.json`: those are UI
 * chrome and are gated on exact key parity across all six locales. Incident
 * copy is *content*, where "no translation yet → show the stored English"
 * is a legitimate, designed outcome rather than a validation failure.
 *
 * Resource addresses (`aws_db_instance.postgres`) are identifiers and are
 * never translated — only prose is.
 */

export type Locale = "en" | "pt-BR" | "es" | "zh" | "hi" | "ar";

type Phrase = Partial<Record<Locale, string>> & { en: string };

/** Root-cause hints, keyed by `root_cause_key` from the API. */
const ROOT_CAUSE: Record<string, Phrase> = {
  policy_blocked: {
    en: "A resource change violated a declared policy rule.",
    "pt-BR": "Uma alteração de recurso violou uma regra de política declarada.",
    es: "Un cambio de recurso infringió una regla de política declarada.",
    zh: "资源变更违反了已声明的策略规则。",
    hi: "एक संसाधन परिवर्तन ने घोषित नीति नियम का उल्लंघन किया।",
    ar: "أدى تغيير في أحد الموارد إلى انتهاك قاعدة سياسة معلنة.",
  },
  drift_detected: {
    en: "Live cloud state diverged from the Terraform plan.",
    "pt-BR": "O estado real na cloud divergiu do plano do Terraform.",
    es: "El estado real en la nube divergió del plan de Terraform.",
    zh: "云端实际状态与 Terraform 计划出现偏差。",
    hi: "लाइव क्लाउड स्थिति Terraform योजना से अलग हो गई।",
    ar: "انحرفت حالة السحابة الفعلية عن خطة Terraform.",
  },
  security_finding: {
    en: "A misconfiguration or insecure default was detected.",
    "pt-BR": "Foi detetada uma configuração incorreta ou um padrão inseguro.",
    es: "Se detectó una configuración incorrecta o un valor predeterminado inseguro.",
    zh: "检测到配置错误或不安全的默认值。",
    hi: "एक गलत कॉन्फ़िगरेशन या असुरक्षित डिफ़ॉल्ट का पता चला।",
    ar: "تم اكتشاف إعداد خاطئ أو قيمة افتراضية غير آمنة.",
  },
  cost_alert: {
    en: "A resource change would exceed the configured cost threshold.",
    "pt-BR": "Uma alteração de recurso excederia o limite de custo configurado.",
    es: "Un cambio de recurso superaría el umbral de coste configurado.",
    zh: "资源变更将超出已配置的成本阈值。",
    hi: "एक संसाधन परिवर्तन कॉन्फ़िगर की गई लागत सीमा से अधिक हो जाएगा।",
    ar: "سيتجاوز تغيير أحد الموارد حد التكلفة المُهيأ.",
  },
  pr_opened: {
    en: "An AI agent opened a PR with high-risk changes.",
    "pt-BR": "Um agente de IA abriu um PR com alterações de alto risco.",
    es: "Un agente de IA abrió un PR con cambios de alto riesgo.",
    zh: "AI 代理提交了包含高风险变更的 PR。",
    hi: "एक AI एजेंट ने उच्च-जोखिम वाले परिवर्तनों के साथ PR खोला।",
    ar: "قام وكيل ذكاء اصطناعي بفتح طلب سحب يتضمن تغييرات عالية الخطورة.",
  },
  generic: {
    en: "Automated detection flagged this event.",
    "pt-BR": "A deteção automática sinalizou este evento.",
    es: "La detección automática marcó este evento.",
    zh: "自动检测标记了此事件。",
    hi: "स्वचालित पहचान ने इस घटना को चिह्नित किया।",
    ar: "أشار الاكتشاف التلقائي إلى هذا الحدث.",
  },
};

/** Suggested-fix hints, keyed by `suggested_fix_key` from the API. */
const SUGGESTED_FIX: Record<string, Phrase> = {
  s3_public: {
    en: "Enable S3 Block Public Access: aws_s3_bucket_public_access_block { block_public_acls = true }",
    "pt-BR":
      "Ative o S3 Block Public Access: aws_s3_bucket_public_access_block { block_public_acls = true }",
    es: "Active S3 Block Public Access: aws_s3_bucket_public_access_block { block_public_acls = true }",
    zh: "启用 S3 Block Public Access：aws_s3_bucket_public_access_block { block_public_acls = true }",
    hi: "S3 Block Public Access सक्षम करें: aws_s3_bucket_public_access_block { block_public_acls = true }",
    ar: "فعّل S3 Block Public Access: aws_s3_bucket_public_access_block { block_public_acls = true }",
  },
  iam_wildcard: {
    en: "Restrict IAM policy resources to specific ARNs instead of wildcard.",
    "pt-BR": "Restrinja os recursos da política IAM a ARNs específicos em vez de usar wildcard.",
    es: "Restrinja los recursos de la política IAM a ARNs específicos en lugar de un comodín.",
    zh: "将 IAM 策略资源限制为特定 ARN，而不是使用通配符。",
    hi: "IAM नीति संसाधनों को वाइल्डकार्ड के बजाय विशिष्ट ARNs तक सीमित करें।",
    ar: "قيّد موارد سياسة IAM بعناوين ARN محددة بدلاً من استخدام حرف البدل.",
  },
  rds_delete: {
    en: "Add lifecycle { prevent_destroy = true } to protect production databases.",
    "pt-BR":
      "Adicione lifecycle { prevent_destroy = true } para proteger bases de dados de produção.",
    es: "Añada lifecycle { prevent_destroy = true } para proteger las bases de datos de producción.",
    zh: "添加 lifecycle { prevent_destroy = true } 以保护生产数据库。",
    hi: "उत्पादन डेटाबेस की सुरक्षा के लिए lifecycle { prevent_destroy = true } जोड़ें।",
    ar: "أضف lifecycle { prevent_destroy = true } لحماية قواعد بيانات الإنتاج.",
  },
  sg_open_ingress: {
    en: "Restrict security group ingress to known CIDR ranges.",
    "pt-BR": "Restrinja o ingress do security group a intervalos CIDR conhecidos.",
    es: "Restrinja el ingress del grupo de seguridad a rangos CIDR conocidos.",
    zh: "将安全组入站规则限制为已知的 CIDR 范围。",
    hi: "सुरक्षा समूह के ingress को ज्ञात CIDR श्रेणियों तक सीमित करें।",
    ar: "قيّد حركة الدخول لمجموعة الأمان بنطاقات CIDR معروفة.",
  },
};

function resolve(catalog: Record<string, Phrase>, key: string | null | undefined, locale: string): string | null {
  if (!key) return null;
  const entry = catalog[key];
  if (!entry) return null;
  return entry[locale as Locale] ?? entry.en;
}

/** Translated root cause, or `null` to fall back to the stored value. */
export function incidentRootCause(key: string | null | undefined, locale: string): string | null {
  return resolve(ROOT_CAUSE, key, locale);
}

/** Translated suggested fix, or `null` to fall back to the stored value. */
export function incidentSuggestedFix(key: string | null | undefined, locale: string): string | null {
  return resolve(SUGGESTED_FIX, key, locale);
}

/**
 * Title prefixes from `_title_from()` in api/v1/ingest.py. Incident titles
 * are stored as "<prefix>: <message>"; only the prefix is static prose, so
 * only the prefix is translated. The message half often carries resource
 * addresses and is left verbatim.
 */
const TITLE_PREFIX: Record<string, { en: string } & Partial<Record<Locale, string>>> = {
  policy_blocked: {
    en: "Policy blocked",
    "pt-BR": "Política bloqueou",
    es: "Política bloqueó",
    zh: "策略已阻止",
    hi: "नीति ने रोका",
    ar: "حظرت السياسة",
  },
  drift_detected: {
    en: "Drift detected",
    "pt-BR": "Desvio detetado",
    es: "Desviación detectada",
    zh: "检测到偏差",
    hi: "ड्रिफ़्ट का पता चला",
    ar: "تم اكتشاف انحراف",
  },
  security_finding: {
    en: "Security finding",
    "pt-BR": "Achado de segurança",
    es: "Hallazgo de seguridad",
    zh: "安全发现",
    hi: "सुरक्षा निष्कर्ष",
    ar: "نتيجة أمنية",
  },
  cost_alert: {
    en: "Cost alert",
    "pt-BR": "Alerta de custo",
    es: "Alerta de coste",
    zh: "成本警报",
    hi: "लागत चेतावनी",
    ar: "تنبيه تكلفة",
  },
  pr_opened: {
    en: "Risky PR",
    "pt-BR": "PR de risco",
    es: "PR arriesgado",
    zh: "高风险 PR",
    hi: "जोखिम भरा PR",
    ar: "طلب سحب محفوف بالمخاطر",
  },
};

/**
 * Translate the static prefix of an incident title, leaving the message
 * half untouched. Returns the original title unchanged when the key is
 * unknown or the stored title does not carry the expected English prefix —
 * so a title written by any other path is never mangled.
 */
export function incidentTitle(
  title: string,
  key: string | null | undefined,
  locale: string,
): string {
  if (!title || !key) return title;
  const entry = TITLE_PREFIX[key];
  if (!entry) return title;
  const sep = `${entry.en}: `;
  if (!title.startsWith(sep)) return title;
  const translated = entry[locale as Locale] ?? entry.en;
  return `${translated}: ${title.slice(sep.length)}`;
}
