name: ci-infra

on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/ci-infra.yml"
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/ci-infra.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: terraform fmt check
        working-directory: infra/terraform
        run: terraform fmt -check -recursive

      - name: terraform validate (dev)
        working-directory: infra/terraform/envs/dev
        run: |
          terraform init -backend=false
          terraform validate

      - name: terraform validate (bootstrap)
        working-directory: infra/terraform/bootstrap
        run: |
          terraform init -backend=false
          terraform validate

  checkov-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov on Terraform
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/terraform
          framework: terraform
          quiet: false
          soft_fail: false
          skip-check: CKV_GCP_12,CKV_GCP_68,CKV_GCP_AR_2,CKV_GCP_IAM_10,CKV_GCP_IAM_3,CKV_GCP_125,CKV2_GCP_IAM_3,CKV_AWS_356,CKV2_AWS_56
