name: ci-web

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - ".github/workflows/ci-web.yml"
  pull_request:
    paths:
      - "apps/web/**"
      - ".github/workflows/ci-web.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/web/pnpm-lock.yaml

      - working-directory: apps/web
        run: pnpm install --no-frozen-lockfile

      - working-directory: apps/web
        run: pnpm lint

      - working-directory: apps/web
        run: pnpm validate-i18n

      - working-directory: apps/web
        run: pnpm build
